// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjwdhudhacsmbofyrhqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtqd2RodWRoYWNzbWJvZnlyaHF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDQ0NDYsImV4cCI6MjA2ODc4MDQ0Nn0.co831qER8rmQEi_mIqLXCjcYGn-uHHnKOfvV2oQ57sQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});